# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j1pop3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j1pop3g/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/j1pop3g/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/j1pop3g/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/j1pop3g/proprietary/etc/wifi/mcs.ini:system/etc/wifi/mcs.ini \
    vendor/samsung/j1pop3g/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/j1pop3g/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/j1pop3g/proprietary/lib/libuvdenoise.so:system/lib/libuvdenoise.so \
    vendor/samsung/j1pop3g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/j1pop3g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/core33g/proprietary/vendor/firmware/vbc_eq:system/vendor/firmware/vbc_eq \